# Generated by Django 6.0.7 on 2026-07-17 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='medico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='medicos.medico'),
        ),
    ]
